"""latest

Revision ID: 1acbb01fce55
Revises: 85cb14725c15
Create Date: 2022-04-11 06:17:15.898457

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1acbb01fce55'
down_revision = '85cb14725c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
