"""new

Revision ID: 2d62abe734cf
Revises: c35ebdf7d662
Create Date: 2022-04-11 06:06:18.670053

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2d62abe734cf'
down_revision = 'c35ebdf7d662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'branches', ['id'])
    op.create_unique_constraint(None, 'companies', ['id'])
    op.create_unique_constraint(None, 'uoms', ['id'])
    op.create_unique_constraint(None, 'warehouses', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='unique')
    op.drop_constraint(None, 'uoms', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'branches', type_='unique')
    # ### end Alembic commands ###
