"""latest

Revision ID: 42a236145c38
Revises: e03893a1f4eb
Create Date: 2022-04-12 02:44:06.015697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '42a236145c38'
down_revision = 'e03893a1f4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authorizations', ['id'])
    op.create_unique_constraint(None, 'modules', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='unique')
    op.drop_constraint(None, 'authorizations', type_='unique')
    # ### end Alembic commands ###
