"""latest

Revision ID: 5b86dfb753d2
Revises: 1acbb01fce55
Create Date: 2022-04-11 06:18:39.173644

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5b86dfb753d2'
down_revision = '1acbb01fce55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
