"""latest

Revision ID: 6fb160b9cfeb
Revises: 5b86dfb753d2
Create Date: 2022-04-11 08:13:43.978443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6fb160b9cfeb'
down_revision = '5b86dfb753d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
