"""latest

Revision ID: 85cb14725c15
Revises: 2d62abe734cf
Create Date: 2022-04-11 06:13:11.648882

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '85cb14725c15'
down_revision = '2d62abe734cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
